### PR TITLE
setup-homebrew: private repositories support

### LINKED ISSUE #236: fatal: could not read Username for 'https://github.com': No such device or address
I've setup a private homebrew tap repo and trying to automate bottles build, but the initial setup step fails:
```yaml
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
```

```console
Run "$GITHUB_ACTION_PATH/main.sh" 'true' 'false'
  "$GITHUB_ACTION_PATH/main.sh" 'true' 'false'
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
From https://github.com/Homebrew/brew
   1eaf8dbbe..ff2985c6a  master     -> origin/master
 * [new tag]             3.2.16     -> 3.2.16
 * [new tag]             3.2.17     -> 3.2.17
Switched to and reset branch 'master'
Branch 'master' set up to track remote branch 'master' from 'origin'.
Your branch is up to date with 'origin/master'.
mkdir: created directory '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/***'
mkdir: created directory '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/***/homebrew-tap'
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/***/homebrew-tap/.git/
'/home/runner/work/homebrew-tap/homebrew-tap' -> '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/***/homebrew-tap'
fatal: could not read Username for 'https://github.com': No such device or address
fatal: could not read Username for 'https://github.com': No such device or address
fatal: could not read Username for 'https://github.com': No such device or address
fatal: could not read Username for 'https://github.com': No such device or address
fatal: could not read Username for 'https://github.com': No such device or address
```

### PR DESCRIPTION
**Pull request by kobim**
fixes #236 

Allow passing the github api token (`GITHUB_TOKEN`) to authenticate with private repositories.

Example:
```yml
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```

### CODE REVIEW

File: setup-homebrew/main.sh [hunk 1]
```diff
@@ -40,6 +41,11 @@ HOMEBREW_REPOSITORY="$(brew --repo)"
 HOMEBREW_CORE_REPOSITORY="$HOMEBREW_REPOSITORY/Library/Taps/homebrew/homebrew-core"
 HOMEBREW_CASK_REPOSITORY="$HOMEBREW_REPOSITORY/Library/Taps/homebrew/homebrew-cask"
 
+# Use an access token to checkout (private repositories)
+if [[ ! -z "${TOKEN}" ]]; then
```
Comment (MikeMcQuaid) [inline setup-homebrew/main.sh:45]:
```suggestion
if [[ -n "${TOKEN}" ]]; then
```

File: setup-homebrew/action.yml [hunk 2]
```diff
@@ -13,6 +13,10 @@ inputs:
     description: Show debugging output
     required: false
     default: false
+  token:
+    description: Token to be used for authenticating to Github (if using private repositories)
```
Comment (MikeMcQuaid) [inline setup-homebrew/action.yml:17]:
```suggestion
    description: Token to be used for GitHub authentication (if using private repositories)
```

**Review by MikeMcQuaid — COMMENTED** [review]
Looks good so far!

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @kobim!
